<?php
 include_once('includes/header.php');
?>


<div class="hb-bannerCont">
	<div class="hb-bannerImgCont">
		<div class="hb-bannerImg">
			<!--<picture>
			     <source media="(max-width: 768px)" srcset="./pi-cloud/images/banners/ppp_mbanner.png">
			      <img  src="./pi-cloud/images/banners/ppp_banner.png" alt="pi-cloud Cloud Backup as a Service Banner" style="width:100%">
      		</picture>-->
      		
      			<picture>
			     <source media="(max-width: 768px)" srcset="./<?= $config['subFolderName'] ?>/images/banners/partner-portal-banner.jpg">
			      <img  src="./<?= $config['subFolderName'] ?>/images/banners/partner-portal-banner.jpg" alt="pi-cloud Cloud Backup as a Service Banner" style="width:100%">
      		</picture>
      		<h2>Partners</h2>
      	
		</div>		
	</div>
</div>
<section id="hb-ptnersCont" style="padding: 40px 0; padding-bottom:0px;">
    	<div class="container">
    	 
    	<ul class="list-inline hb-btn_cl" style="width:60%; margin:0px auto;">
    	   <li><img src="./<?= $config['subFolderName'] ?>/images/partners-new-banner.jpg" width="300px"/></li>
      				<li>
      					<a href="https://pidatacenters.com/pi-cloud/partnerportal" target="_blank" class="global-button">Register</a>
      				</li>
      				<li><a href="https://pidatacenters.com/pi-cloud/partnerportal/login" target="_blank" class="global-button">Login</a></li>
      			</ul>
      			</div>
    </section>


<section id="hb-ptnersCont" style="padding: 0px 0;">
	<div class="container">
		<div class="hb-patAdv">
			<div class="hb-patnerLeft">
				<h1>GTM Advantage</h1>
				<p>The Pi Partner Program gives you a new prospect of growth along with the ever growing data center leader in the Indian industry.The data pool generated by today’s enterprises has hiked the demand for data center and cloud services. The exponential drift in adoption and the need for intelligent data extraction & application call for smart and agile data centers which can scale to specific requirements.</p>
				
				<p>We continue to invest in the right technologies & infrastructure for our partners to leverage and expand their horizon, add that zing to their positioning and remain industry leaders in their own space.</p>
			</div>
			<div class="hb-patnerRight">
				<p>
					<img src="./<?= $config['subFolderName'] ?>/images/Company-pana1.png" alt="Gtm adv">
				</p>
			</div>
		</div>
	</div>
</section>







<section>
	<div class="container">
		<div class="hb-ourCintInfo">
			<h2 class="text-center">Tech Advantage</h2>
			<p>Being a Smart and Software Defined Strategic Data Center (SDSDC) organisation, we provide you an incredible opportunity, as a partner, to deliver the best to your customer’s ever growing IT infrastructure innovation needs. You have a unique advantage to partner with Asia’s largest <a href="https://uptimeinstitute.com/uptime-institute-awards/list/datacenter/amaravati/818" target="_blank">Uptime Institute TIER IV Certified</a> Data Center organisation with an access to scale-at-will capacity and uncompromising quality. This gives you the opportunity to build in a strong colocation and hosting service line into your own solution stack.The true-blue and award-winning cloud fabric, pi-cloud<sup>®</sup>, is a stable and highly scalable enterprise cloud platform @Pi<sup>®</sup>. The flexibility, Software Defined Network (SDN) and Storage delivered out of pi-cloud<sup>®</sup>, makes it a strong proposition for you as a Partner to leverage.The unique proposition of self-service provisioning makes it a technology marvel to take it to your customers.</p>
						
				<ul class="list-inline hb-ourListCont ">
				<li>
					<span>
						<img src="./pi-cloud/images/partners/w1_ico.png" alt="Gtm adv">
					</span>
					<p>Positioning partner as leader</p>
				</li>
				<li>
					<span>
						<img src="./pi-cloud/images/partners/w2_ico.png" alt="uptime">
					</span>
					<p>99.995% uptime is guaranteed</p>
				</li>
				<li>
					<span>
						<img src="./pi-cloud/images/partners/w3_ico.png" alt="state">
					</span>
					<p>State-Of-The-Art <br>Infrastructure</p>
				</li>
				<li>
					<span>
						<img src="./pi-cloud/images/partners/w4_ico.png" alt="patners">
					</span>
					<p>Modular<br>architecture model</p>
				</li>
				<li>
					<span>
						<img src="./pi-cloud/images/partners/w5_ico.png" alt="patners">
					</span>
					<p>Scale-at-will</p>
				</li>
				<li>
					<span>
						<img src="./pi-cloud/images/partners/w6_ico.png" alt="patners">
					</span>
					<p>Self service</p>
				</li>
				<li>
					<span>
						<img src="./pi-cloud/images/partners/w7_ico.png" alt="patners">
					</span>
					<p>Agile solution</p>
				</li>
			</ul>	
		</div>
	</div>
</section>

<!-- <section>
	<div class="container">
		<div class="hb-tecPartners">
			<h3>Technology Partners</h3>
			<ul class="list-inline hb-companys hb-fourC text-center">
				<li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li>
				<li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li>
				<li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li>

			</ul>
		</div>
	</div>
</section>
<section>
	<div class="container">
		<div class="hb-tecPartners">
			<h3>Business Partners</h3>
			<ul class="list-inline hb-companys hb-fourC text-center">
				<li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li>
				<li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li>
				<li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li>

			</ul>
		</div>
	</div>
</section> -->

<section>
	<div class="container">
		<div class="hb-whatDoGet">
			<h3>What Do You Get As A Partner?</h3>
			<p>The Integration Partner Program allows our partners to work with us to offer an expanded solution stack out of their stable.Our flexible benefit stack supports and contributes to your Go-To-Market strategy. In all the phases across customer interaction, be it pre-sales, sales operations, sales management, branding air cover, or a combination of any of the stated, we deliver value and differentiation to our partners to generate business.</p>
			
		</div>
		<ul class="list-inline hb-etDoImg hb-fourC">
			<li>
				<div class="hb-helBox">
					<p>
						<span><img src="./pi-cloud/images/partners/ppp1.png" alt="patners"></span>
						<small class="hb-hoCont">The essence of Pi Partner Program lies in its approach around collaborative planning and integrated go to market strategy. It is desinged to deliver quantified results and customer experience, while achiving common business goals.</small>
					</p>
					<h3>Collaborative Planning</h3>
				</div>
			</li>
			<li>
				<div class="hb-helBox">
					<p>
						<span><img src="./pi-cloud/images/partners/ppp2.png" alt="patners"></span>
						<small class="hb-hoCont">Well appointed partner referral program for consultant partners and system integrators to leverage for succesfully referring one of the world's best datacenters and enterpise cloud services to industry peers/acquintances.</small>
					</p>
					<h3>Referral Bonus</h3>
				</div>
			</li>
			<li>
				<div class="hb-helBox">
					<p>
						<span><img src="./pi-cloud/images/partners/ppp3.png" alt="patners"></span>
						<small class="hb-hoCont">Partner access to a strong layer of business enabling functions to help achieve business outcome across customer lifecycle. Handholding on branding , pre-sales and sales support.</small>
					</p>
					<h3>Virtual Alliance Team</h3>
				</div>
			</li>
			<li>
				<div class="hb-helBox">
					<p>
						<span><img src="./pi-cloud/images/partners/ppp4.png" alt="patners"></span>
						<small class="hb-hoCont">Sandbox environments as a incubation centers for the partner or partner's customers, for platform familiarisation and solution readiness, at no additional cost.</small>
					</p>
					<h3>Free Sandbox Environment</h3>
				</div>
			</li>
		</ul>
		<ul class="list-inline hb-etDoImg hb-thirC">
			<li>
				<div class="hb-helBox">
					<p>
						<span><img src="./pi-cloud/images/partners/ppp5.png" alt="patners"></span>
						<small class="hb-hoCont">Well appointed class room training content and modules, supported by perodic training webinars, by industry champoins. Enabling partners to come up to speed to the latest in the data center and cloud services space.</small>
					</p>
					<h3>Training & Workshop</h3>
				</div>
			</li>
			<li>
				<div class="hb-helBox">
					<p>
						<span><img src="./pi-cloud/images/partners/ppp6.png" alt="patners"></span>
						<small class="hb-hoCont">Unleash the unique opportunity to share knowledge, increase brand awareness, and strengthen relationships across industries, through co-partnered industry events.</small>
					</p>
					<h3>Co-Partnered Industry Events</h3>
				</div>
			</li>
			<li>
				<div class="hb-helBox"		>
					<p>
						<span><img src="./pi-cloud/images/partners/ppp7.png" alt="patners"> </span>
						<small class="hb-hoCont">Get access to industry trends , marketing collaterals and opportunities to co-market through webinars, eBooks, and website listing.</small>
					</p>
					<h3>Marketing Collateral</h3>
				</div>
			</li>	
		</ul>
	</div>
</section>



<div class="hb-ourPartners" style="margin-top: 36px">
	<div class="container">
		<div class="hb-ourCint">
			<h2 class="text-center">Our Partner Tracks</h2>
			<p class="text-center">Our partners bring in unique capabilities in terms of their industry reach and holistic nature of business. Cognizing this, Pi Partner Program offers varied partner tracks for you to choose your best fit.</p>
			<ul class="list-inline hb-ourListCont">
				<li>
					<span>
						<img src="./pi-cloud/images/partners/p1.svg" alt="patners">
					</span>
					<p>Technology Alliances</p>
				</li>
				<li>
					<span>
						<img src="./pi-cloud/images/partners/p2.svg" alt="patners">
					</span>
					<p>System Integrators</p>
				</li>
				<li>
					<span>
						<img src="./pi-cloud/images/partners/p3.svg" alt="patners">
					</span>
					<p>Resellers</p>
				</li>
				<li>
					<span>
						<img src="./pi-cloud/images/partners/p4.svg" alt="patners">
					</span>
					<p>ISVs</p>
				</li>
				<li>
					<span>
						<img src="./pi-cloud/images/partners/p5.svg" alt="patners">
					</span>
					<p>Managed Service Providers</p>
				</li>
				<li>
					<span>
						<img src="./pi-cloud/images/partners/p6.svg" alt="patners">
					</span>
					<p>OEM Partnerships</p>
				</li>
				<li>
					<span>
						<img src="./pi-cloud/images/partners/p7.svg" alt="patners">
					</span>
					<p>Consulting Partners</p>
				</li>

			</ul>
		</div>
	</div>
</div>

<style type="text/css">
    .hb_loginCtas {
    background-image: url("./<?= $config['subFolderName'] ?>/partner-portal-banner.jpg");
    width: 100%;
}
    
</style>
<?php
	include_once('includes/footer.php');
?>