<?php
return[
    'options' => [
        'APPROVED' => 'approved',
        'REJECTED' => 'rejected',
        'PENDING' => 'pending',
    ],
    'user_types' => [
        'PIADMIN' => 'admin',
        'PARTNERADMIN' => 'partner_admin',
        'PARTNERSALES' => 'partner_sales',
    ],
    'partners_is_verified' => [
        'PENDING' => 0,
        'APPROVED' => 2,
        'REJECTED' => 3,
    ],
    'mails' => [
        'PARTNER_APPROVAL_MAIL_SUBJECT' => env('PARTNER_APPROVAL_MAIL_SUBJECT', 'Welcome to Pi DATACENTERS : Registered Business Partner Onboarding Acknowledgement'),
        'PARTNER_REJECTION_MAIL_SUBJECT' => env('PARTNER_REJECTION_MAIL_SUBJECT', 'Partner registration rejected'),
        'PIPELINE_CREATION_MAIL_SUBJECT' => env('PIPELINE_CREATION_MAIL_SUBJECT', 'New pipeline created'),
        'PIPELINE_UPDATE_MAIL_SUBJECT' => env('PIPELINE_UPDATE_MAIL_SUBJECT', 'Pipeline Updated'),
        'PIPELINE_APPROVAL_MAIL_SUBJECT' => env('PIPELINE_APPROVAL_MAIL_SUBJECT', 'Pipeline Approval'),
        'PIPELINE_REJECTION_MAIL_SUBJECT' => env('PIPELINE_REJECTION_MAIL_SUBJECT', 'Pipeline Rejection'),
        'GTMFundReq_CREATION_MAIL_SUBJECT' => env('GTMFundReq_CREATION_MAIL_SUBJECT', 'GTM Fund Request Created'),
        'GTMFundReq_APPROVAL_MAIL_SUBJECT' => env('GTMFundReq_APPROVAL_MAIL_SUBJECT', 'GTM Fund Request Approval'),
        'GTMFundReq_REJECTION_MAIL_SUBJECT' => env('GTMFundReq_REJECTION_MAIL_SUBJECT', 'GTM Fund Request Not Approved'),
        'GTMFundReq_DELETION_MAIL_SUBJECT' => env('GTMFundReq_DELETION_MAIL_SUBJECT', 'GTM Fund Request Deleted'),
        'GTMCAMPAIGN_CREATION_MAIL_SUBJECT' => env('GTMCAMPAIGN_CREATION_MAIL_SUBJECT', 'Joint Media Campaign Request Created'),
        'GTMCAMPAIGN_APPROVAL_MAIL_SUBJECT' => env('GTMCAMPAIGN_APPROVAL_MAIL_SUBJECT', 'Joint Media Campaign Request Approval'),
        'GTMCAMPAIGN_REJECTION_MAIL_SUBJECT' => env('GTMCAMPAIGN_REJECTION_MAIL_SUBJECT', 'Joint Media Campaign Request Not Approved'),
        'GTMCAMPAIGN_DELETION_MAIL_SUBJECT' => env('GTMCAMPAIGN_DELETION_MAIL_SUBJECT', 'Joint Media Campaign Request Deleted'),
        'GTMJEReq_CREATION_MAIL_SUBJECT' => env('GTMJEReq_CREATION_MAIL_SUBJECT', 'Joint Event Request Created'),
        'GTMJEReq_APPROVAL_MAIL_SUBJECT' => env('GTMJEReq_APPROVAL_MAIL_SUBJECT', 'Joint Event Request Approval'),
        'GTMJEReq_REJECTION_MAIL_SUBJECT' => env('GTMJEReq_REJECTION_MAIL_SUBJECT', 'Joint Event Request Not Approved'),
        'GTMJEReq_DELETION_MAIL_SUBJECT' => env('GTMJEReq_DELETION_MAIL_SUBJECT', 'Joint Event Request Deleted'),
        'GTMCOLLATERAL_CREATION_MAIL_SUBJECT' => env('GTMCOLLATERAL_CREATION_MAIL_SUBJECT', 'Joint Marketing Collateral Request Created'),
        'GTMCOLLATERAL_APPROVAL_MAIL_SUBJECT' => env('GTMCOLLATERAL_APPROVAL_MAIL_SUBJECT', 'Joint Marketing Collateral Request Approval'),
        'GTMCOLLATERAL_REJECTION_MAIL_SUBJECT' => env('GTMCOLLATERAL_REJECTION_MAIL_SUBJECT', 'Joint Marketing Collateral Request Not Approved'),
        'GTMCOLLATERAL_DELETION_MAIL_SUBJECT' => env('GTMCOLLATERAL_DELETION_MAIL_SUBJECT', 'Joint Marketing Collateral Request Deleted'),
        'MAIL_DEFAULT_FROM' => 'partnerprogram@pidatacenters.com',
        'MAIL_TEST_TO' => 'debmalya@pidatacenters.com',
        'PI_ADMIN_MAIL' => 'bidmanagement@pidatacenters.com',
        'PI_ADMIN_MAIL2' => 'debmalya@pidatacenters.com',
        'PI_ADMIN_MAIL3' => 'bhaswati.de@pidatacenters.com',
        'MAIL_TEST_FROM' => 'debmalya@pidatacenters.com',
    ],
    'auth' => [
        'FORGOT_PASSWORD_MESSAGE' => env('FORGOT_PASSWORD_RESPONSE_MESSAGE', "Check your email! A link to change your password has been sent in the email"),
        'FORGOT_PASSWORD_MAIL_SUBJECT' => env('FORGOT_PASSWORD_MAIL_SUBJECT', "Reset your password"),
    ],
    'rh_emails' => [
        "Rajesh Kariya"=>"lakshmijyothi@pidatacenters.com",
        "Debmalya Dey Roy"=>"lakshmijyothi@pidatacenters.com",
        "SN Sarma"=>"lakshmijyothi@pidatacenters.com",
        "Rama Chandra"=>"lakshmijyothi@pidatacenters.com",
    ],
    'ro_emails' => [
        "Sujog Dwivedi"=>"sujog.dwivedi@pidatacenters.com",
        "Abshishek Shedge"=>"abhishek.shedge@pidatacenters.com",
        "Vijay Sharma"=>"vijay.sharma@pidatacenters.com",
        "Shikha Dixit"=>"shikha.d@pidatacenters.com",
        "Rajesh Kariya"=>"rajesh.kariya@pidatacenters.com",
        "Ankur Rohila "=>"ankur.rohila@pidatacenters.com",
        "Varun Kumar Verma"=>"varun.k@pidatacenters.com",
        "Roopam Jain"=>"roopam.jain@pidatacenters.com",
        "Debmalya Dey Roy"=>"debmalya@pidatacenters.com",
        "SN Sarma"=>"snsarma@pidatacenters.com",
        "Laxman Rao"=>"laxman.rao@pidatacenters.com",
        "Vijayan Appasamy"=>"vijayan@pidatacenters.com",
        "Pawan Kumar Wasi"=>"pawan.vasi@pidatacenters.com",
        "Rama Chandra"=>"ramachandra@pidatacenters.com",
        "Rohan Chandrahas"=>"rohan.c@pidatacenters.com",
        "Geo Kurian"=>"geo@pidatacenters.com",
        "Ayan Ghosh"=>"ayan.ghosh@pidatacenters.com",
        "Dhruv Narang"=>"dhruv.narang@pidatacenters.com",
        "Sajan Deokar"=>"sajan.deokar@pidatacenters.com",
        "Shruti Dubey"=>"shruti.dubey@pidatacenters.com",
        "Shreeya Swain"=>"shreeya.swain@pidatacenters.com",
        "Sidharth Joshi"=>"sidharth.joshi@pidatacenters.com",
        "Soumya Subhankar"=>"soumya.subhankar@pidatacenters.com",
        "Vatsal Agarwal"=>"vatsal.agarwal@pidatacenters.com",
        "Manoj Manila"=>"m.manoj@pidatacenters.com",
        "Vishal Tyagi"=>"vishal.tyagi@pidatacenters.com",
        "Akshit Akarsh Shrivastva"=>"akshit.shrivastva@pidatacenters.com",
        "Jobin PJ"=>"jobin.pj@pidatacenters.com",
    ],
    
];
